<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ws_groupsandusers"
 *
 * Auto generated by Extension Builder 2015-03-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Groups and users',
	'description' => 'Shows groups and users generated in typo3 backend',
	'category' => 'plugin',
	'author' => 'Martin Hollmann',
	'author_email' => 'martin@webschuppen.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.9.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);